# Generated by Django 3.1.1 on 2020-09-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='description',
            new_name='telefone',
        ),
        migrations.AddField(
            model_name='reserva',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='reservas'),
        ),
    ]
